// Mock data for the healthcare platform

export const mockDoctors = [
  {
    id: "1",
    name: "Dr. Priya Sharma",
    specialization: "General Physician",
    qualification: "MBBS, MD",
    experience: "12 years",
    rating: 4.8,
    reviews: 245,
    fee: 500,
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&h=300&fit=crop",
    available: true,
    nextSlot: "Today, 4:00 PM",
    providerType: "Doctor"
  },
  {
    id: "2",
    name: "Dr. Rajesh Kumar",
    specialization: "Cardiologist",
    qualification: "MBBS, DM Cardiology",
    experience: "18 years",
    rating: 4.9,
    reviews: 512,
    fee: 1000,
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&h=300&fit=crop",
    available: true,
    nextSlot: "Tomorrow, 10:00 AM",
    providerType: "Doctor"
  },
  {
    id: "3",
    name: "Dr. Anjali Verma",
    specialization: "Pediatrician",
    qualification: "MBBS, DCH",
    experience: "8 years",
    rating: 4.7,
    reviews: 189,
    fee: 600,
    image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=300&h=300&fit=crop",
    available: false,
    nextSlot: "Dec 20, 9:00 AM",
    providerType: "Doctor"
  },
];

export const mockNurses = [
  {
    id: "4",
    name: "Sister Mary Thomas",
    specialization: "Home Care Nurse",
    qualification: "B.Sc Nursing",
    experience: "10 years",
    rating: 4.9,
    reviews: 156,
    fee: 800,
    image: "https://images.unsplash.com/photo-1527613426441-4da17471b66d?w=300&h=300&fit=crop",
    available: true,
    services: ["Wound Care", "IV Administration", "Patient Monitoring"],
    providerType: "Nurse"
  },
  {
    id: "5",
    name: "Nurse Priya Patel",
    specialization: "ICU Trained Nurse",
    qualification: "GNM, ICU Certification",
    experience: "6 years",
    rating: 4.8,
    reviews: 98,
    fee: 1000,
    image: "https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=300&h=300&fit=crop",
    available: true,
    services: ["Critical Care", "Ventilator Support", "Emergency Care"],
    providerType: "Nurse"
  },
];

// Physiotherapy providers
export const mockPhysiotherapists = [
  {
    id: "6",
    name: "Dr. Vikram Rao",
    specialization: "Sports Physiotherapy",
    qualification: "BPT, MPT",
    experience: "10 years",
    rating: 4.7,
    reviews: 134,
    fee: 700,
    image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&h=300&fit=crop",
    available: true,
    services: ["Sports Injury Recovery", "Post-Surgery Rehabilitation", "Pain Management"],
    providerType: "Physiotherapy"
  },
  {
    id: "7",
    name: "Meera Krishnan",
    specialization: "Orthopedic Physiotherapy",
    qualification: "BPT, Certified Therapist",
    experience: "7 years",
    rating: 4.6,
    reviews: 89,
    fee: 600,
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&h=300&fit=crop",
    available: true,
    services: ["Joint Mobility", "Muscle Strengthening", "Balance Training"],
    providerType: "Physiotherapy"
  },
];

// Lab Technician providers
export const mockLabTechnicians = [
  {
    id: "8",
    name: "Suresh Reddy",
    specialization: "Clinical Laboratory",
    qualification: "B.Sc MLT, DMLT",
    experience: "12 years",
    rating: 4.8,
    reviews: 201,
    fee: 400,
    image: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=300&h=300&fit=crop",
    available: true,
    services: ["Blood Tests", "Urine Analysis", "Sample Collection"],
    providerType: "Lab Technician"
  },
  {
    id: "9",
    name: "Kavita Joshi",
    specialization: "Pathology Lab",
    qualification: "B.Sc MLT",
    experience: "8 years",
    rating: 4.7,
    reviews: 156,
    fee: 350,
    image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=300&h=300&fit=crop",
    available: true,
    services: ["Diagnostic Testing", "Report Generation", "Home Sample Collection"],
    providerType: "Lab Technician"
  },
];

export const mockCareTakers = [
  {
    id: "1",
    name: "Ramesh Singh",
    specialization: "Elder Care",
    experience: "8 years",
    rating: 4.7,
    reviews: 89,
    fee: 500,
    image: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=300&h=300&fit=crop",
    available: true,
    services: ["Daily Assistance", "Medication Reminders", "Mobility Support"],
  },
  {
    id: "2",
    name: "Sunita Devi",
    specialization: "Post-Surgery Care",
    experience: "5 years",
    rating: 4.6,
    reviews: 67,
    fee: 600,
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&h=300&fit=crop",
    available: true,
    services: ["Recovery Support", "Physiotherapy Assistance", "Wound Care"],
  },
];

export const mockAppointments = [
  {
    id: "1",
    patientName: "Rahul Gupta",
    patientAge: 35,
    patientGender: "Male",
    patientPhone: "+91 98765 43210",
    patientEmail: "rahul.gupta@email.com",
    patientAddress: "123 Green Park, New Delhi - 110016",
    patientBloodGroup: "O+",
    providerName: "Dr. Priya Sharma",
    providerType: "Doctor",
    providerSpecialization: "General Physician",
    providerQualification: "MBBS, MD",
    providerPhone: "+91 98765 00001",
    providerFee: 500,
    date: "Dec 18, 2024",
    time: "10:00 AM",
    startTime: "10:00 AM",
    endTime: "10:30 AM",
    duration: "30 minutes",
    status: "confirmed",
    reason: "Regular Checkup",
    symptoms: "Fever, Body ache, Headache",
    notes: "Patient reports mild fever for last 2 days",
    appointmentType: "Home Visit",
    bookingDate: "Dec 15, 2024",
  },
  {
    id: "2",
    patientName: "Anita Desai",
    patientAge: 58,
    patientGender: "Female",
    patientPhone: "+91 98765 43211",
    patientEmail: "anita.desai@email.com",
    patientAddress: "456 Park Street, Mumbai - 400001",
    patientBloodGroup: "B+",
    providerName: "Sister Mary Thomas",
    providerType: "Nurse",
    providerSpecialization: "Home Care Nurse",
    providerQualification: "B.Sc Nursing",
    providerPhone: "+91 98765 00002",
    providerFee: 800,
    date: "Dec 19, 2024",
    time: "2:00 PM",
    startTime: "2:00 PM",
    endTime: "3:00 PM",
    duration: "1 hour",
    status: "pending",
    reason: "Post-surgery wound care",
    symptoms: "Surgical wound monitoring",
    notes: "Post-operative care after knee surgery. Wound dressing required.",
    appointmentType: "Home Visit",
    bookingDate: "Dec 16, 2024",
  },
  {
    id: "3",
    patientName: "Vikram Patel",
    patientAge: 72,
    patientGender: "Male",
    patientPhone: "+91 98765 43212",
    patientEmail: "vikram.patel@email.com",
    patientAddress: "789 MG Road, Bangalore - 560001",
    patientBloodGroup: "A+",
    providerName: "Ramesh Singh",
    providerType: "Care Taker",
    providerSpecialization: "Elder Care",
    providerQualification: "Certified Caretaker",
    providerPhone: "+91 98765 00003",
    providerFee: 500,
    date: "Dec 17, 2024",
    time: "9:00 AM",
    startTime: "9:00 AM",
    endTime: "6:00 PM",
    duration: "9 hours",
    status: "completed",
    reason: "Elder care assistance",
    symptoms: "Mobility support needed",
    notes: "Daily care assistance. Medication reminders at 10 AM, 2 PM, and 8 PM.",
    appointmentType: "Full Day Care",
    bookingDate: "Dec 10, 2024",
  },
  {
    id: "4",
    patientName: "Priya Mehta",
    patientAge: 42,
    patientGender: "Female",
    patientPhone: "+91 98765 43213",
    patientEmail: "priya.mehta@email.com",
    patientAddress: "321 Sector 15, Noida - 201301, Uttar Pradesh",
    patientBloodGroup: "AB+",
    providerName: "Dr. Rajesh Kumar",
    providerType: "Doctor",
    providerSpecialization: "Cardiologist",
    providerQualification: "MBBS, DM Cardiology",
    providerPhone: "+91 98765 00004",
    providerFee: 1000,
    date: "Dec 20, 2024",
    time: "11:00 AM",
    startTime: "11:00 AM",
    endTime: "11:45 AM",
    duration: "45 minutes",
    status: "confirmed",
    reason: "Heart Checkup",
    symptoms: "Chest pain, Shortness of breath",
    notes: "Patient has history of hypertension. ECG and blood pressure monitoring required.",
    appointmentType: "Clinic Visit",
    bookingDate: "Dec 18, 2024",
  },
  {
    id: "5",
    patientName: "Sanjay Reddy",
    patientAge: 28,
    patientGender: "Male",
    patientPhone: "+91 98765 43214",
    patientEmail: "sanjay.reddy@email.com",
    patientAddress: "567 Banjara Hills, Hyderabad - 500034, Telangana",
    patientBloodGroup: "O-",
    providerName: "Dr. Vikram Rao",
    providerType: "Physiotherapy",
    providerSpecialization: "Sports Physiotherapy",
    providerQualification: "BPT, MPT",
    providerPhone: "+91 98765 00005",
    providerFee: 700,
    date: "Dec 21, 2024",
    time: "4:00 PM",
    startTime: "4:00 PM",
    endTime: "5:00 PM",
    duration: "1 hour",
    status: "pending",
    reason: "Sports Injury Recovery",
    symptoms: "Knee pain, Muscle stiffness",
    notes: "Football injury last week. Need physiotherapy for knee rehabilitation.",
    appointmentType: "Home Visit",
    bookingDate: "Dec 19, 2024",
  },
  {
    id: "6",
    patientName: "Kavita Singh",
    patientAge: 55,
    patientGender: "Female",
    patientPhone: "+91 98765 43215",
    patientEmail: "kavita.singh@email.com",
    patientAddress: "890 Civil Lines, Jaipur - 302006, Rajasthan",
    patientBloodGroup: "B-",
    providerName: "Nurse Priya Patel",
    providerType: "Nurse",
    providerSpecialization: "ICU Trained Nurse",
    providerQualification: "GNM, ICU Certification",
    providerPhone: "+91 98765 00006",
    providerFee: 1000,
    date: "Dec 22, 2024",
    time: "8:00 AM",
    startTime: "8:00 AM",
    endTime: "12:00 PM",
    duration: "4 hours",
    status: "confirmed",
    reason: "Post-surgery home care",
    symptoms: "Recovery monitoring, IV administration",
    notes: "Recent cardiac surgery. Requires IV medication and vitals monitoring every 2 hours.",
    appointmentType: "Extended Home Care",
    bookingDate: "Dec 20, 2024",
  },
  {
    id: "7",
    patientName: "Arun Kumar",
    patientAge: 65,
    patientGender: "Male",
    patientPhone: "+91 98765 43216",
    patientEmail: "arun.kumar@email.com",
    patientAddress: "234 Anna Nagar, Chennai - 600040, Tamil Nadu",
    patientBloodGroup: "A-",
    providerName: "Suresh Reddy",
    providerType: "Lab Technician",
    providerSpecialization: "Clinical Laboratory",
    providerQualification: "B.Sc MLT, DMLT",
    providerPhone: "+91 98765 00007",
    providerFee: 400,
    date: "Dec 23, 2024",
    time: "7:00 AM",
    startTime: "7:00 AM",
    endTime: "7:30 AM",
    duration: "30 minutes",
    status: "pending",
    reason: "Blood Test - Fasting",
    symptoms: "Routine health checkup",
    notes: "Fasting blood sugar, Lipid profile, Complete blood count required. Patient fasting since 10 PM yesterday.",
    appointmentType: "Home Sample Collection",
    bookingDate: "Dec 21, 2024",
  },
  {
    id: "8",
    patientName: "Meera Krishnan",
    patientAge: 38,
    patientGender: "Female",
    patientPhone: "+91 98765 43217",
    patientEmail: "meera.krishnan@email.com",
    patientAddress: "678 Koramangala, Bangalore - 560095, Karnataka",
    patientBloodGroup: "O+",
    providerName: "Dr. Anjali Verma",
    providerType: "Doctor",
    providerSpecialization: "Pediatrician",
    providerQualification: "MBBS, DCH",
    providerPhone: "+91 98765 00008",
    providerFee: 600,
    date: "Dec 24, 2024",
    time: "3:00 PM",
    startTime: "3:00 PM",
    endTime: "3:30 PM",
    duration: "30 minutes",
    status: "confirmed",
    reason: "Child vaccination",
    symptoms: "Routine vaccination schedule",
    notes: "5-year-old child - DTP booster vaccination due. Bring vaccination card.",
    appointmentType: "Clinic Visit",
    bookingDate: "Dec 20, 2024",
  },
  {
    id: "9",
    patientName: "Deepak Sharma",
    patientAge: 50,
    patientGender: "Male",
    patientPhone: "+91 98765 43218",
    patientEmail: "deepak.sharma@email.com",
    patientAddress: "456 Vastrapur, Ahmedabad - 380015, Gujarat",
    patientBloodGroup: "AB-",
    providerName: "Meera Krishnan",
    providerType: "Physiotherapy",
    providerSpecialization: "Orthopedic Physiotherapy",
    providerQualification: "BPT, Certified Therapist",
    providerPhone: "+91 98765 00009",
    providerFee: 600,
    date: "Dec 25, 2024",
    time: "10:00 AM",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    duration: "1 hour",
    status: "cancelled",
    reason: "Back pain therapy",
    symptoms: "Lower back pain, Limited mobility",
    notes: "Chronic lower back pain. Requires spinal mobilization and strengthening exercises. Cancelled by patient - personal emergency.",
    appointmentType: "Home Visit",
    bookingDate: "Dec 22, 2024",
  },
  {
    id: "10",
    patientName: "Sunita Joshi",
    patientAge: 62,
    patientGender: "Female",
    patientPhone: "+91 98765 43219",
    patientEmail: "sunita.joshi@email.com",
    patientAddress: "789 Sadashiv Peth, Pune - 411030, Maharashtra",
    patientBloodGroup: "B+",
    providerName: "Kavita Joshi",
    providerType: "Lab Technician",
    providerSpecialization: "Pathology Lab",
    providerQualification: "B.Sc MLT",
    providerPhone: "+91 98765 00010",
    providerFee: 350,
    date: "Dec 16, 2024",
    time: "6:30 AM",
    startTime: "6:30 AM",
    endTime: "7:00 AM",
    duration: "30 minutes",
    status: "completed",
    reason: "Diabetes screening",
    symptoms: "Routine diabetic checkup",
    notes: "HbA1c test completed. Reports shared with patient. Follow-up consultation recommended.",
    appointmentType: "Home Sample Collection",
    bookingDate: "Dec 14, 2024",
  },
];

export const mockTestimonials = [
  {
    id: "1",
    name: "Priya Mehta",
    role: "Patient",
    content: "Healthy Touch made it so easy to find a reliable home nurse for my father. The care has been exceptional!",
    rating: 5,
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
  },
  {
    id: "2",
    name: "Dr. Amit Shah",
    role: "Doctor",
    content: "As a provider, this platform has helped me reach more patients who need home consultations. Excellent system!",
    rating: 5,
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=100&h=100&fit=crop",
  },
  {
    id: "3",
    name: "Ravi Kumar",
    role: "Family Member",
    content: "Finding quality care for my elderly mother was always stressful. Healthy Touch changed that completely.",
    rating: 5,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
  },
];

export const mockStats = {
  totalPatients: 15420,
  totalProviders: 892,
  totalAppointments: 45230,
  citiesCovered: 28,
};

export const mockPatientProfile = {
  id: "1",
  name: "Rahul Gupta",
  email: "rahul.gupta@email.com",
  phone: "+91 98765 43210",
  age: 35,
  gender: "Male",
  bloodGroup: "O+",
  address: "123 Green Park, New Delhi - 110016",
  emergencyContact: "+91 98765 43211",
};

export const mockMedicalRecords = [
  {
    id: "1",
    date: "Dec 15, 2024",
    doctor: "Dr. Priya Sharma",
    diagnosis: "Seasonal Flu",
    prescription: "Paracetamol 500mg, Vitamin C",
    notes: "Rest advised for 3 days. Increase fluid intake.",
  },
  {
    id: "2",
    date: "Nov 20, 2024",
    doctor: "Dr. Rajesh Kumar",
    diagnosis: "Routine Heart Checkup",
    prescription: "Continue current medication",
    notes: "ECG normal. Next checkup in 6 months.",
  },
];

export type UserRole = "patient" | "doctor" | "nurse" | "caretaker" | "admin";

export interface User {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  avatar?: string;
}

export const mockUsers: User[] = [
  { id: "1", name: "Rahul Gupta", email: "patient@demo.com", role: "patient" },
  { id: "2", name: "Dr. Priya Sharma", email: "doctor@demo.com", role: "doctor" },
  { id: "3", name: "Sister Mary", email: "nurse@demo.com", role: "nurse" },
  { id: "4", name: "Admin User", email: "admin@demo.com", role: "admin" },
];
